
name: Docker # nome da rotina

on:
  workflow_call: #quando outra rotina chamar ela, ela vai ser executada

jobs:
  docker: # nome do job
    runs-on: ubuntu-latest # só vai rodar no ambiente do ubuntu
    steps:
    - uses: actions/checkout@v3 # utilizar dos dados que estão em nosso repositorui? sim!
# tasks:
    - name: setup Docker Build # foi ali do lado, no marketplace e procurei poro Docekr build
      uses: docker/setup-buildx-action@v3.8.0 # (nome/repositorio@versao) ela mandou eu colocar esse use aqui

    - name: Docker Login
  # copiei la no marketplace o de docker login
      uses: docker/login-action@v3.3.0
      with:
        # registro no docker hub
          username: gustavoDocker910 # gustavoDocker910
        # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

          # vai buildar e colocar a imagem em algum reposiotrio
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.12.0
      with:
        context: . # Qual pasta esta os nossos arquivos
        file: ./Dockerfile # caminho para o arquivo dockerfile
           
        push: true # colocar nossa imagem em algum lugar, no caso, no docker hub
        tags: gustavoDocker910/go_cli:${{ github.ref_name }} # cria o nome e utiliza a branch atual com a varavel: ${{github.ref_name}}
     
